config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'healthcheck/status'

  resources :scheduled_tasks
  post 'scheduled_tasks/:id/clear_execution' => 'scheduled_tasks#clear_execution', as: :clear_scheduled_task_execution

  require 'sidekiq/web'
  require 'sidekiq-status/web'
  Sidekiq::Web.set :session_secret, Rails.application.secrets.secret_key_base
  mount Sidekiq::Web => '/sidekiq'

end

app/models/scheduled_task.rb
class ScheduledTask < ActiveRecord::Base
  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :klass, presence: true
  validates :quantity, presence: true, if: :recurring?
  validates :period, presence: true, if: :recurring?

  def frequency
    return nil if quantity.blank?

    quantity.send(period.pluralize)
  end

  def recurring_interval
    return nil unless recurring?

    "#{quantity} #{period.pluralize(quantity)}"
  end

  def tz
    tz? ? read_attribute(:tz) : Time.zone.name
  end

  def can_run_at?(ts=nil)
    raise Exception('Must provide a valid Time object') if ts.nil?
    return true if not_before.blank? and not_after.blank?

    return false if not_before? and ts < not_before
    return false if not_after? and ts > not_after

    true
  end

  def can_run?
    can_run_at?(Time.now)
  end

  def if?(ts=nil)
    if not recurring?
      return false if executed_at?
    end

    can_run_at?(ts)
  end

  def ignored_attributes
    [ :executed_at ]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_settings do |s|
    s.key :profile, defaults: { name: nil, time_zone: 'Eastern Time (US & Canada)' }
  end

  def name
    settings(:profile).name
  end

  def name=(new_name)
    settings(:profile).name = new_name
  end

  def time_zone
    settings(:profile).time_zone
  end

  def time_zone=(new_tz)
    settings(:profile).time_zone = new_tz
  end

  def display_name
    name || email
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_raven_context!

  # Uncomment when devise is activated
  # before_action :authenticate_user!
  # around_action :set_time_zone

  def set_raven_context!
    # Uncomment when devise is activated
    # Raven.user_context(id: current_user.try(:id), email: current_user.try(:email))
    Raven.extra_context(params: params.to_hash, url: request.url)
  end

  def get_user_time_zone
    return 'Eastern Time (US & Canada)' if not user_signed_in?
    current_user.settings(:profile).time_zone
  end

  def set_time_zone(&block)
    Time.use_zone(get_user_time_zone, &block)
  end

  def json_request?
    request.format.json?
  end

  def options_request?
    request.method == :options
  end
end

app/controllers/healthcheck_controller.rb
class HealthcheckController < ApplicationController
  skip_before_action :authenticate_user!
  skip_around_action :set_time_zone

  respond_to :plain

  def status
    render plain: 'Application OK'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/scheduled_tasks_controller.rb
class ScheduledTasksController < ApplicationController
  before_action :set_scheduled_task, only: [:show, :edit, :update, :destroy, :clear_execution]

  # GET /scheduled_tasks
  # GET /scheduled_tasks.json
  def index
    @scheduled_tasks = ScheduledTask.all
  end

  # GET /scheduled_tasks/1
  # GET /scheduled_tasks/1.json
  def show
  end

  # GET /scheduled_tasks/new
  def new
    @scheduled_task = ScheduledTask.new
  end

  # GET /scheduled_tasks/1/edit
  def edit
  end

  # POST /scheduled_tasks
  # POST /scheduled_tasks.json
  def create
    @scheduled_task = ScheduledTask.new(scheduled_task_params)

    respond_to do |format|
      if @scheduled_task.save
        format.html { redirect_to @scheduled_task, notice: 'Scheduled task was successfully created.' }
        format.json { render :show, status: :created, location: @scheduled_task }
      else
        format.html { render :new }
        format.json { render json: @scheduled_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /scheduled_tasks/1
  # PATCH/PUT /scheduled_tasks/1.json
  def update
    respond_to do |format|
      if @scheduled_task.update(scheduled_task_params)
        format.html { redirect_to @scheduled_task, notice: 'Scheduled task was successfully updated.' }
        format.json { render :show, status: :ok, location: @scheduled_task }
      else
        format.html { render :edit }
        format.json { render json: @scheduled_task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scheduled_tasks/1
  # DELETE /scheduled_tasks/1.json
  def destroy
    @scheduled_task.destroy
    respond_to do |format|
      format.html { redirect_to scheduled_tasks_url, notice: 'Scheduled task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /scheduled_tasks/1/clear_execution
  # POST /scheduled_tasks/1/clear_execution.json
  def clear_execution
    @scheduled_task.update(executed_at: nil)
    respond_to do |format|
      format.html { redirect_to @scheduled_task, notice: 'Scheduled task was successfully cleared of its last execution time.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_scheduled_task
      @scheduled_task = ScheduledTask.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def scheduled_task_params
      params.require(:scheduled_task).permit(:quantity, :period, :name, :klass, {args: []}, :at, :tz, :recurring, :not_before, :not_after, :executed_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(title_text)
    content_for(:title) { title_text }
  end
end

app/helpers/healthcheck_helper.rb
module HealthcheckHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scheduled_tasks_helper.rb
module ScheduledTasksHelper
  def periods
    [ :second, :minute, :hour, :day, :week, :month ]
  end

  def jobs
    Dir[File.join(File.dirname(__FILE__), '../jobs/**/*_job.rb')].map { |f| File.basename(f, '.*').camelize }
  end
end

app/views/application/_messages.html.haml
- flash.each do |k, v|
  %div.alert-horizontal{ class: "alert-#{k}" }
    %a.close{ href: '#', data: { dismiss: :alert } }= ''
    %ul
      %li= v

app/views/application/_nav.html.haml
%a#menuLink.menu-link{ href: '#menu' }
  %span= ''

#menu
  .pure-menu
    %a.pure-menu-heading{ href: '#' }= 'NewApp'

    %ul.pure-menu-list
      %li.pure-menu-item
        =link_to root_path, { class: [ 'pure-menu-link' ] } do
          Home

    %ul.pure-menu-list
      %li.pure-menu-item
        =link_to scheduled_tasks_path, { class: [ 'pure-menu-link' ] } do
          Scheduled Tasks

app/views/home/index.html.haml
.header
  %h1 NewApp

.content
  Hello.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "NewApp: " + (content_for?(:title) ? yield(:title) : 'Default App Title') + (Rails.env.development? ? ' (development)' : '')
    %meta{ name: :viewport, content: 'width=device-width, initial-scale=1.0' }
    =stylesheet_link_tag    'http://yui.yahooapis.com/pure/0.6.0/pure-min.css', media: 'all'.freeze
    =stylesheet_link_tag    'http://yui.yahooapis.com/pure/0.6.0/grids-responsive-min.css', media: 'all'.freeze
    =stylesheet_link_tag    'https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css', media: 'all'.freeze
    =stylesheet_link_tag    'application', media: 'all'.freeze, 'data-turbolinks-track' => true
    =stylesheet_link_tag    'chosen', media: 'all'.freeze, 'data-turbolinks-track' => true
    =javascript_include_tag 'application', 'data-turbolinks-track' => true
    =csrf_meta_tags

  %body
    #container
      = render 'nav'

      #main
        = render 'messages'

        =yield

app/views/scheduled_tasks/_form.html.haml
= form_for @scheduled_task, html: { class: [ 'pure-form', 'pure-form-aligned' ] } do |f|
  - if @scheduled_task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@scheduled_task.errors.count, "error")} prohibited this scheduled_task from being saved:"
      %ul
        - @scheduled_task.errors.full_messages.each do |msg|
          %li= msg

  .field.pure-control-group
    = f.label :recurring, 'Recurring?'
    = f.check_box :recurring

  .field.pure-control-group
    = f.label :quantity, 'Frequency'
    = f.text_field :quantity, class: [ 'pure-input-1-4' ]
    = f.select :period, periods.map(&:to_s).map(&:capitalize).map(&:pluralize).map(&:to_s).zip(periods)

  .field.pure-control-group
    = f.label :name, 'Task Name'
    = f.text_field :name, class: [ 'pure-input-1-3' ]

  .field.pure-control-group
    = f.label :klass, 'Job Class'
    = f.select :klass, jobs

  = react_component 'TaskArguments', { className: 'pure-input-1-2', 'formName': 'scheduled_task', arguments: @scheduled_task.args || [] }

  .field.pure-control-group
    = f.label :at, 'At (HH:MM)'
    = f.text_field :at, class: [ 'pure-input-1-3' ]

  .field.pure-control-group
    = f.label :tz, 'Time Zone'
    = f.text_field :tz, class: [ 'pure-input-1-3' ]

  .field.pure-control-group
    = f.label :not_before
    = f.datetime_local_field :not_before

  .field.pure-control-group
    = f.label :not_after
    = f.datetime_local_field :not_after

  .actions.pure-controls
    = f.submit 'Save', class: [ 'pure-button' ]

app/views/scheduled_tasks/edit.html.haml
.header
  %h1 Editing Scheduled Task
  %h2= @scheduled_task.name

.content
  .subnav
    =link_to scheduled_tasks_path, class: [ 'pure-button' ] do
      %i.fa.fa-lg.fa-arrow-circle-up= ''
      Up

    =link_to @scheduled_task, class: [ 'pure-button' ] do
      %i.fa.fa-lg.fa-tasks= ''
      Show

  = render 'form'

app/views/scheduled_tasks/index.html.haml
.header
  %h1 Scheduled Tasks
  %br

.content
  .subnav
    =link_to new_scheduled_task_path, class: [ 'pure-button', 'pure-button-primary' ] do
      %i.fa.fa-lg.fa-plus-circle= ''
      New Task

  %table.pure-table.pure-table-horizontal
    %thead
      %tr
        %th Name
        %th Job Class
        %th Recurring?
        %th At?
        %th Time Zone
        %th Last Executed
        %th
        %th
        %th

    %tbody
      - @scheduled_tasks.each do |scheduled_task|
        %tr
          %td= scheduled_task.name
          %td= scheduled_task.klass
          %td
            - if scheduled_task.recurring?
              Yes, every #{scheduled_task.recurring_interval}
            - else
              No
          %td= scheduled_task.at
          %td= scheduled_task.tz
          %td
            - if scheduled_task.executed_at?
              =scheduled_task.executed_at.strftime('%B %-e, %Y %H:%M%p')
            - else
              (never)
          %td= link_to 'Show', scheduled_task
          %td= link_to 'Edit', edit_scheduled_task_path(scheduled_task)
          %td= link_to 'Destroy', scheduled_task, :method => :delete, :data => { :confirm => 'Are you sure?' }

app/views/scheduled_tasks/new.html.haml
.header
  %h1 Create a Scheduled Task
  %br

.content
  .subnav
    =link_to scheduled_tasks_path, class: [ 'pure-button' ] do
      %i.fa.fa-lg.fa-arrow-circle-left= ''
      Back

  = render 'form'

app/views/scheduled_tasks/show.html.haml
.header
  %h1= @scheduled_task.name
  %h2 Scheduled Tasks

.content
  .subnav
    =link_to scheduled_tasks_path, class: [ 'pure-button' ] do
      %i.fa.fa-lg.fa-arrow-circle-up= ''
      Up

    =link_to edit_scheduled_task_path(@scheduled_task), class: [ 'pure-button' ] do
      %i.fa.fa-lg.fa-edit= ''
      Edit

    =link_to @scheduled_task, method: :delete, data: { :confirm => 'Are you sure?' }, class: [ 'pure-button' ] do
      %i.fa.fa-lg.fa-times-circle= ''
      Delete

    =link_to clear_scheduled_task_execution_path(@scheduled_task), method: :post, class: [ 'pure-button' ] do
      %i.fa.fa-lg.fa-clock-o= ''
      Clear Execution

  %table.pure-table.pure-table-horizontal
    %tbody
      %tr
        %td
          %b Name
        %td
          = @scheduled_task.name

      %tr
        %td
          %b Job Class
        %td
          = @scheduled_task.klass

      %tr
        %td
          %b Recurring?
        %td
          - if @scheduled_task.recurring?
            %b
              Yes, every #{@scheduled_task.recurring_interval}
          - else
            No

      %tr
        %td
          %b Job Arguments
        %td
          - if not @scheduled_task.args.blank?
            %pre= @scheduled_task.args
          - else
            (no arguments)

      %tr
        %td
          %b At
        %td
          - if not @scheduled_task.at.blank?
            = @scheduled_task.at
          - else
            (no specific time)

      %tr
        %td
          %b Time Zone
        %td
          = @scheduled_task.tz

      %tr
        %td
          %b Don't Run Before
        %td
          = @scheduled_task.not_before

      %tr
        %td
          %b Don't Run After
        %td
          = @scheduled_task.not_after

      %tr
        %td
          %b Last Executed At
        %td
          - if @scheduled_task.executed_at?
            = @scheduled_task.executed_at.strftime('%B %-e, %Y %H:%M:%S %p')
          - else
            (never)